name: Ipv6

on:
  schedule:
  - cron: "30 1,13 * * *"
  workflow_dispatch:

jobs:
  generate-ipv6-m3u:
    permissions:
      contents: write # 确保有写入权限，这是解决上一个错误的关键
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库 - 关键修改在这里
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 提供token以便后续推送
          persist-credentials: true # 关键！持久化凭据，让后续步骤能执行git push

      # ... 其他步骤（Setup Python, Install dependencies, Run script）保持不变 ...

      # 提交生成的 ipv6.m3u 文件到仓库
      - name: Commit and push ipv6.m3u
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ipv6.m3u
          git commit -m "Update ipv6.m3u (automated)"
          git push
