name: Ipv6

on:
  schedule:
  - cron: "30 1,13 * * *"
  workflow_dispatch: # 支持手动触发

jobs:
  generate-ipv6-m3u:
    # 授予这个作业（job）所需的特定权限
    permissions: 
      contents: write # 授予写入仓库内容的权限
    runs-on: ubuntu-latest

    steps:
      # ... 前面的步骤保持不变 ...
      
      # 提交生成的 ipv6.m3u 文件到仓库
      - name: Commit and push ipv6.m3u
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ipv6.m3u
          git commit -m "Update ipv6.m3u (automated)"
          git push
